modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="superpickaxe"
version="1.0"
displayName="Super Pickaxe Mod"
description='''
A mod that adds a 3x3x3 mining pickaxe to Minecraft!
'''

[[dependencies.superpickaxe]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.superpickaxe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
